backend:
  name: github
  repo: jgaya/condetodo
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: thumbnail, label: 'Featured Image', widget: image }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["news","pelis"]